document.addEventListener('DOMContentLoaded', () => {
    fetchData();

    // Search functionality
    const searchInput = document.getElementById('search-input');
    searchInput.addEventListener('input', (e) => {
        filterResources(e.target.value);
    });
});

let resourcesData = [];

async function fetchData() {
    const grid = document.getElementById('resource-grid');
    const lastUpdated = document.getElementById('last-updated');
    const rgCount = document.getElementById('rg-count');
    const locCount = document.getElementById('location-count');

    try {
        // Attempt to fetch data generated by the workflow
        const response = await fetch('data.json');

        if (!response.ok) {
            throw new Error('Data not found');
        }

        const data = await response.json();

        // Handle if data is wrapped or direct array
        resourcesData = Array.isArray(data) ? data : (data ? [data] : []);

        if (resourcesData.length === 0) {
            grid.innerHTML = '<div class="loading-state"><p>No resources found.</p></div>';
            return;
        }

        renderResources(resourcesData);
        updateStats(resourcesData);

        const now = new Date();
        lastUpdated.textContent = `Updated: ${now.toLocaleTimeString()}`;

        // Remove blinking dot after load
        document.querySelector('.status-dot').style.animation = 'none';
        document.querySelector('.status-dot').style.opacity = '1';

    } catch (error) {
        console.error('Error fetching data:', error);

        // If data.json is missing (local dev), use mock data
        if (location.hostname === 'localhost' || location.protocol === 'file:') {
            console.log('Using mock data for local development');
            useMockData();
        } else {
            grid.innerHTML = `
                <div class="error-state">
                    <i class="fa-solid fa-triangle-exclamation" style="font-size: 2rem;"></i>
                    <h3>Unable to load data</h3>
                    <p>Ensure the GitHub Action has run successfully.</p>
                </div>
            `;
            lastUpdated.textContent = 'Connection Failed';
            document.querySelector('.status-dot').style.backgroundColor = 'var(--error)';
            document.querySelector('.status-dot').style.boxShadow = '0 0 8px var(--error)';
        }
    }
}

function renderResources(resources) {
    const grid = document.getElementById('resource-grid');
    grid.innerHTML = '';

    resources.forEach(rg => {
        const card = document.createElement('div');
        card.className = 'resource-card';

        // Extract properties (adjust based on actual Azure JSON output)
        const name = rg.ResourceGroupName || rg.Name || 'Unknown';
        const location = rg.Location || 'Unknown';
        const state = rg.ProvisioningState || 'Unknown';
        const id = rg.ResourceId || rg.Id || '';
        const subscriptionId = id.split('/')[2] || '...';

        card.innerHTML = `
            <div class="card-header">
                <div class="card-icon">
                    <i class="fa-solid fa-cube"></i>
                </div>
                <span class="tag">${state}</span>
            </div>
            <div class="card-title" title="${name}">${name}</div>
            <div class="card-details">
                <div class="detail-row">
                    <span class="detail-label">Location</span>
                    <span class="detail-value">${location}</span>
                </div>
                <div class="detail-row">
                    <span class="detail-label">Sub ID</span>
                    <span class="detail-value" title="${subscriptionId}">${subscriptionId.substring(0, 8)}...</span>
                </div>
            </div>
        `;
        grid.appendChild(card);
    });
}

function updateStats(resources) {
    const rgCount = document.getElementById('rg-count');
    const locCount = document.getElementById('location-count');

    rgCount.textContent = resources.length;

    const locations = new Set(resources.map(r => r.Location || 'Unknown'));
    locCount.textContent = locations.size;
}

function filterResources(query) {
    const lowerQuery = query.toLowerCase();
    const filtered = resourcesData.filter(r => {
        const name = (r.ResourceGroupName || r.Name || '').toLowerCase();
        const location = (r.Location || '').toLowerCase();
        return name.includes(lowerQuery) || location.includes(lowerQuery);
    });
    renderResources(filtered);
}

function useMockData() {
    const mockData = [
        { ResourceGroupName: 'rg-prod-001', Location: 'eastus', ProvisioningState: 'Succeeded', ResourceId: '/subs/123/rg/rg-prod-001' },
        { ResourceGroupName: 'rg-dev-001', Location: 'westeurope', ProvisioningState: 'Succeeded', ResourceId: '/subs/123/rg/rg-dev-001' },
        { ResourceGroupName: 'rg-test-lab', Location: 'eastus', ProvisioningState: 'Succeeded', ResourceId: '/subs/123/rg/rg-test-lab' },
        { ResourceGroupName: 'rg-monitoring', Location: 'northeurope', ProvisioningState: 'Succeeded', ResourceId: '/subs/123/rg/rg-monitoring' },
        { ResourceGroupName: 'rg-backup-vault', Location: 'westus', ProvisioningState: 'Succeeded', ResourceId: '/subs/123/rg/rg-backup-vault' }
    ];
    resourcesData = mockData;
    renderResources(mockData);
    updateStats(mockData);
    document.getElementById('last-updated').textContent = 'Mock Mode';
}
